# Generated by Django 4.2.5 on 2025-04-18 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('customer_review_rank', models.IntegerField()),
                ('author', models.CharField(max_length=15)),
                ('author_profile_img', models.ImageField(blank=True, upload_to='author_profiles/')),
                ('author_info', models.TextField()),
                ('author_works', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(blank=True, upload_to='')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tts/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('reading_date', models.DateField()),
                ('cover_img', models.ImageField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='books.book')),
            ],
        ),
    ]
